namespace MVCBlog.Migrations
{
    using MVCBlog.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<MVCBlog.Models.MVCBlogContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(MVCBlog.Models.MVCBlogContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //

            var users = new List<User>
            {
                new User { Login = "user1", Password = "qwerty1", EmailAddress = "user1@mail.com" },
                new User { Login = "user2", Password = "qwerty2", EmailAddress = "user2@mail.com" },
                new User { Login = "user3", Password = "qwerty3", EmailAddress = "user3@mail.com" },
                new User { Login = "user4", Password = "qwerty4", EmailAddress = "user4@mail.com" },
                new User { Login = "user5", Password = "qwerty5", EmailAddress = "user5@mail.com" }
            };

            users.ForEach(s => context.Users.AddOrUpdate(p => p.Login, s));
            context.SaveChanges();

            var categories = new List<Category>
            {
                new Category { CategoryName = "Style"},
                new Category { CategoryName = "Health"},
                new Category { CategoryName = "Business"},
                new Category { CategoryName = "Market"},
                new Category { CategoryName = "Sport"},
                new Category { CategoryName = "Pets"}
            };

            categories.ForEach(s => context.Categories.AddOrUpdate(p => p.CategoryName, s));
            context.SaveChanges();

            var articles = new List<Article>
            {
                new Article { ArticleName = "Article 1", UserId = 1, CategoryId = 3, ArticleText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia a neque sagittis rutrum. Ut tincidunt metus lectus, at auctor metus porta ut. Quisque ultrices semper ipsum. Phasellus et gravida purus. Pellentesque eu ligula eget elit rhoncus sollicitudin non quis lectus. In et leo dolor. Pellentesque quis metus felis. Sed ultrices nulla vitae elit ullamcorper pellentesque. Nullam posuere pharetra imperdiet. Vestibulum augue arcu, lobortis in porttitor sit amet, sollicitudin non augue. Vestibulum in justo est. Ut mauris mi, pretium et eleifend eu, sollicitudin et purus. Praesent consectetur risus at egestas fermentum. Nulla mollis massa nec ante cursus, id vulputate nunc ultrices. Aliquam vel nunc nec sem sagittis consectetur. Integer auctor fermentum aliquam. Proin a lobortis tellus. Etiam gravida mauris tellus, ut venenatis ligula convallis eu. Aenean pulvinar erat quam, id condimentum tortor blandit in. Nullam ultricies vel turpis quis cursus. Integer suscipit mollis magna eget gravida. Proin luctus massa ut eros convallis, vitae convallis mauris pharetra. Donec aliquam, lorem quis ultrices consectetur, lorem mauris volutpat nibh, vel condimentum eros elit eget magna. In hac habitasse platea dictumst. Fusce blandit, nibh id feugiat euismod, lacus sapien consequat neque, at aliquam ipsum nisi ac magna. Duis porttitor ullamcorper arcu. Aenean a consequat eros. Aliquam erat volutpat. Aenean id ullamcorper nunc. Mauris eu magna mollis enim rutrum lacinia. Vestibulum auctor metus in dui faucibus feugiat. Aliquam fermentum leo a fringilla sodales. Nulla elementum semper semper. Suspendisse ut mi eu nulla molestie pellentesque in quis purus. Nunc nec est non lacus ornare tempor. Sed dictum molestie ante ut feugiat. Morbi venenatis nulla et erat accumsan, vestibulum cursus mi placerat. Aenean vehicula, purus a sollicitudin lobortis, ante lacus vulputate sapien, quis sagittis eros quam ac dolor. Pellentesque viverra a nibh quis vulputate. Aenean condimentum pulvinar neque, aliquet sagittis arcu bibendum in. Phasellus sed venenatis mauris. Pellentesque at pulvinar lectus. Sed condimentum ipsum eu sollicitudin egestas. Mauris eget quam nulla. Integer vulputate vitae arcu ut condimentum. Quisque at quam ut eros condimentum tincidunt et a odio. Vivamus laoreet nunc vel nisi vestibulum, at vestibulum mi tincidunt. Pellentesque pellentesque at nibh vitae eleifend." },
                new Article { ArticleName = "Article 2", UserId = 1, CategoryId = 5, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 3", UserId = 2, CategoryId = 2, ArticleText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia a neque sagittis rutrum. Ut tincidunt metus lectus, at auctor metus porta ut. Quisque ultrices semper ipsum. Phasellus et gravida purus. Pellentesque eu ligula eget elit rhoncus sollicitudin non quis lectus. In et leo dolor. Pellentesque quis metus felis. Sed ultrices nulla vitae elit ullamcorper pellentesque. Nullam posuere pharetra imperdiet. Vestibulum augue arcu, lobortis in porttitor sit amet, sollicitudin non augue. Vestibulum in justo est. Ut mauris mi, pretium et eleifend eu, sollicitudin et purus. Praesent consectetur risus at egestas fermentum. Nulla mollis massa nec ante cursus, id vulputate nunc ultrices. Aliquam vel nunc nec sem sagittis consectetur. Integer auctor fermentum aliquam. Proin a lobortis tellus. Etiam gravida mauris tellus, ut venenatis ligula convallis eu. Aenean pulvinar erat quam, id condimentum tortor blandit in. Nullam ultricies vel turpis quis cursus. Integer suscipit mollis magna eget gravida. Proin luctus massa ut eros convallis, vitae convallis mauris pharetra. Donec aliquam, lorem quis ultrices consectetur, lorem mauris volutpat nibh, vel condimentum eros elit eget magna. In hac habitasse platea dictumst. Fusce blandit, nibh id feugiat euismod, lacus sapien consequat neque, at aliquam ipsum nisi ac magna. Duis porttitor ullamcorper arcu. Aenean a consequat eros. Aliquam erat volutpat. Aenean id ullamcorper nunc. Mauris eu magna mollis enim rutrum lacinia. Vestibulum auctor metus in dui faucibus feugiat. Aliquam fermentum leo a fringilla sodales. Nulla elementum semper semper. Suspendisse ut mi eu nulla molestie pellentesque in quis purus. Nunc nec est non lacus ornare tempor. Sed dictum molestie ante ut feugiat. Morbi venenatis nulla et erat accumsan, vestibulum cursus mi placerat. Aenean vehicula, purus a sollicitudin lobortis, ante lacus vulputate sapien, quis sagittis eros quam ac dolor. Pellentesque viverra a nibh quis vulputate. Aenean condimentum pulvinar neque, aliquet sagittis arcu bibendum in. Phasellus sed venenatis mauris. Pellentesque at pulvinar lectus. Sed condimentum ipsum eu sollicitudin egestas. Mauris eget quam nulla. Integer vulputate vitae arcu ut condimentum. Quisque at quam ut eros condimentum tincidunt et a odio. Vivamus laoreet nunc vel nisi vestibulum, at vestibulum mi tincidunt. Pellentesque pellentesque at nibh vitae eleifend." },
                new Article { ArticleName = "Article 4", UserId = 2, CategoryId = 3, ArticleText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia a neque sagittis rutrum. Ut tincidunt metus lectus, at auctor metus porta ut. Quisque ultrices semper ipsum. Phasellus et gravida purus. Pellentesque eu ligula eget elit rhoncus sollicitudin non quis lectus. In et leo dolor. Pellentesque quis metus felis. Sed ultrices nulla vitae elit ullamcorper pellentesque. Nullam posuere pharetra imperdiet. Vestibulum augue arcu, lobortis in porttitor sit amet, sollicitudin non augue. Vestibulum in justo est. Ut mauris mi, pretium et eleifend eu, sollicitudin et purus. Praesent consectetur risus at egestas fermentum. Nulla mollis massa nec ante cursus, id vulputate nunc ultrices. Aliquam vel nunc nec sem sagittis consectetur. Integer auctor fermentum aliquam. Proin a lobortis tellus. Etiam gravida mauris tellus, ut venenatis ligula convallis eu. Aenean pulvinar erat quam, id condimentum tortor blandit in. Nullam ultricies vel turpis quis cursus. Integer suscipit mollis magna eget gravida. Proin luctus massa ut eros convallis, vitae convallis mauris pharetra. Donec aliquam, lorem quis ultrices consectetur, lorem mauris volutpat nibh, vel condimentum eros elit eget magna. In hac habitasse platea dictumst. Fusce blandit, nibh id feugiat euismod, lacus sapien consequat neque, at aliquam ipsum nisi ac magna. Duis porttitor ullamcorper arcu. Aenean a consequat eros. Aliquam erat volutpat. Aenean id ullamcorper nunc. Mauris eu magna mollis enim rutrum lacinia. Vestibulum auctor metus in dui faucibus feugiat. Aliquam fermentum leo a fringilla sodales. Nulla elementum semper semper. Suspendisse ut mi eu nulla molestie pellentesque in quis purus. Nunc nec est non lacus ornare tempor. Sed dictum molestie ante ut feugiat. Morbi venenatis nulla et erat accumsan, vestibulum cursus mi placerat. Aenean vehicula, purus a sollicitudin lobortis, ante lacus vulputate sapien, quis sagittis eros quam ac dolor. Pellentesque viverra a nibh quis vulputate. Aenean condimentum pulvinar neque, aliquet sagittis arcu bibendum in. Phasellus sed venenatis mauris. Pellentesque at pulvinar lectus. Sed condimentum ipsum eu sollicitudin egestas. Mauris eget quam nulla. Integer vulputate vitae arcu ut condimentum. Quisque at quam ut eros condimentum tincidunt et a odio. Vivamus laoreet nunc vel nisi vestibulum, at vestibulum mi tincidunt. Pellentesque pellentesque at nibh vitae eleifend." },
                new Article { ArticleName = "Article 5", UserId = 3, CategoryId = 1, ArticleText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia a neque sagittis rutrum. Ut tincidunt metus lectus, at auctor metus porta ut. Quisque ultrices semper ipsum. Phasellus et gravida purus. Pellentesque eu ligula eget elit rhoncus sollicitudin non quis lectus. In et leo dolor. Pellentesque quis metus felis. Sed ultrices nulla vitae elit ullamcorper pellentesque. Nullam posuere pharetra imperdiet. Vestibulum augue arcu, lobortis in porttitor sit amet, sollicitudin non augue. Vestibulum in justo est. Ut mauris mi, pretium et eleifend eu, sollicitudin et purus. Praesent consectetur risus at egestas fermentum. Nulla mollis massa nec ante cursus, id vulputate nunc ultrices. Aliquam vel nunc nec sem sagittis consectetur. Integer auctor fermentum aliquam. Proin a lobortis tellus. Etiam gravida mauris tellus, ut venenatis ligula convallis eu. Aenean pulvinar erat quam, id condimentum tortor blandit in. Nullam ultricies vel turpis quis cursus. Integer suscipit mollis magna eget gravida. Proin luctus massa ut eros convallis, vitae convallis mauris pharetra. Donec aliquam, lorem quis ultrices consectetur, lorem mauris volutpat nibh, vel condimentum eros elit eget magna. In hac habitasse platea dictumst. Fusce blandit, nibh id feugiat euismod, lacus sapien consequat neque, at aliquam ipsum nisi ac magna. Duis porttitor ullamcorper arcu. Aenean a consequat eros. Aliquam erat volutpat. Aenean id ullamcorper nunc. Mauris eu magna mollis enim rutrum lacinia. Vestibulum auctor metus in dui faucibus feugiat. Aliquam fermentum leo a fringilla sodales. Nulla elementum semper semper. Suspendisse ut mi eu nulla molestie pellentesque in quis purus. Nunc nec est non lacus ornare tempor. Sed dictum molestie ante ut feugiat. Morbi venenatis nulla et erat accumsan, vestibulum cursus mi placerat. Aenean vehicula, purus a sollicitudin lobortis, ante lacus vulputate sapien, quis sagittis eros quam ac dolor. Pellentesque viverra a nibh quis vulputate. Aenean condimentum pulvinar neque, aliquet sagittis arcu bibendum in. Phasellus sed venenatis mauris. Pellentesque at pulvinar lectus. Sed condimentum ipsum eu sollicitudin egestas. Mauris eget quam nulla. Integer vulputate vitae arcu ut condimentum. Quisque at quam ut eros condimentum tincidunt et a odio. Vivamus laoreet nunc vel nisi vestibulum, at vestibulum mi tincidunt. Pellentesque pellentesque at nibh vitae eleifend." },
                new Article { ArticleName = "Article 6", UserId = 3, CategoryId = 1, ArticleText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia a neque sagittis rutrum. Ut tincidunt metus lectus, at auctor metus porta ut. Quisque ultrices semper ipsum. Phasellus et gravida purus. Pellentesque eu ligula eget elit rhoncus sollicitudin non quis lectus. In et leo dolor. Pellentesque quis metus felis. Sed ultrices nulla vitae elit ullamcorper pellentesque. Nullam posuere pharetra imperdiet. Vestibulum augue arcu, lobortis in porttitor sit amet, sollicitudin non augue. Vestibulum in justo est. Ut mauris mi, pretium et eleifend eu, sollicitudin et purus. Praesent consectetur risus at egestas fermentum. Nulla mollis massa nec ante cursus, id vulputate nunc ultrices. Aliquam vel nunc nec sem sagittis consectetur. Integer auctor fermentum aliquam. Proin a lobortis tellus. Etiam gravida mauris tellus, ut venenatis ligula convallis eu. Aenean pulvinar erat quam, id condimentum tortor blandit in. Nullam ultricies vel turpis quis cursus. Integer suscipit mollis magna eget gravida. Proin luctus massa ut eros convallis, vitae convallis mauris pharetra. Donec aliquam, lorem quis ultrices consectetur, lorem mauris volutpat nibh, vel condimentum eros elit eget magna. In hac habitasse platea dictumst. Fusce blandit, nibh id feugiat euismod, lacus sapien consequat neque, at aliquam ipsum nisi ac magna. Duis porttitor ullamcorper arcu. Aenean a consequat eros. Aliquam erat volutpat. Aenean id ullamcorper nunc. Mauris eu magna mollis enim rutrum lacinia. Vestibulum auctor metus in dui faucibus feugiat. Aliquam fermentum leo a fringilla sodales. Nulla elementum semper semper. Suspendisse ut mi eu nulla molestie pellentesque in quis purus. Nunc nec est non lacus ornare tempor. Sed dictum molestie ante ut feugiat. Morbi venenatis nulla et erat accumsan, vestibulum cursus mi placerat. Aenean vehicula, purus a sollicitudin lobortis, ante lacus vulputate sapien, quis sagittis eros quam ac dolor. Pellentesque viverra a nibh quis vulputate. Aenean condimentum pulvinar neque, aliquet sagittis arcu bibendum in. Phasellus sed venenatis mauris. Pellentesque at pulvinar lectus. Sed condimentum ipsum eu sollicitudin egestas. Mauris eget quam nulla. Integer vulputate vitae arcu ut condimentum. Quisque at quam ut eros condimentum tincidunt et a odio. Vivamus laoreet nunc vel nisi vestibulum, at vestibulum mi tincidunt. Pellentesque pellentesque at nibh vitae eleifend." },
                new Article { ArticleName = "Article 7", UserId = 4, CategoryId = 5, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 8", UserId = 4, CategoryId = 2, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 9", UserId = 5, CategoryId = 4, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 10", UserId = 5, CategoryId = 2, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 11", UserId = 1, CategoryId = 1, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 12", UserId = 2, CategoryId = 4, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 13", UserId = 3, CategoryId = 6, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 14", UserId = 4, CategoryId = 6, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." },
                new Article { ArticleName = "Article 15", UserId = 5, CategoryId = 5, ArticleText = "Lorem ipsum dolor sit amet, saperet nominavi expetendis mei at. Est dicit molestiae theophrastus an, et mel altera meliore, pro habeo viderer an. Per natum praesent eloquentiam ei, persius quaeque prodesset quo eu. Pro eleifend explicari at, mea dicat choro fabulas te, alii soluta tincidunt an ius. Per in etiam admodum, veri semper cu ius. Magna oblique dolorum sit ea, id his explicari voluptaria. Tempor evertitur in usu, usu ad cibo summo omnium. In feugiat eleifend incorrupte nec. No utamur expetenda vim, ei nec ponderum efficiantur. In cum utinam delenit salutandi, dolore suavitate ei vis. Wisi soluta putant te sit, ceteros adipiscing his ei, sanctus honestatis in mea. Ei usu iudicabit definiebas, latine alterum sit ex, posse consetetur est ne. Et mei feugait sadipscing, alii etiam offendit nec ex. Pri at scripta fierent, et eam case eius bonorum. Has eu possim meliore, ei eos everti tamquam fabellas, an mea quod error eruditi. Te ius eius minim omittam, usu an laoreet copiosae consequuntur, semper disputando eam eu. Cum quis legimus in, vis diam error simul te, sit ad harum menandri. Per et latine dolorem disputando, eu doming facilis tacimates vix, ad oblique platonem duo. Purto tritani ut qui, tantas evertitur constituam ius no, pro vidit audire adolescens ei. Autem dicat utroque in vel, et audiam indoctum salutatus usu." }
            };

            articles.ForEach(s => context.Articles.AddOrUpdate(p => p.ArticleName, s));
            context.SaveChanges();

            var comments = new List<Comment>
            {
                new Comment { UserId = 1, ArticleId = 1, CommentDate = DateTime.Parse("2013-01-01T12:34:56"), CommentText = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus." },
                new Comment { UserId = 5, ArticleId = 2, CommentDate = DateTime.Parse("2013-03-04T12:34:56"), CommentText = "Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim." },
                new Comment { UserId = 5, ArticleId = 3, CommentDate = DateTime.Parse("2013-05-14T12:34:56"), CommentText = "Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo." },
                new Comment { UserId = 2, ArticleId = 4, CommentDate = DateTime.Parse("2013-02-09T12:34:56"), CommentText = "Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. " },
                new Comment { UserId = 4, ArticleId = 5, CommentDate = DateTime.Parse("2013-11-26T12:34:56"), CommentText = "Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem." },
                new Comment { UserId = 1, ArticleId = 6, CommentDate = DateTime.Parse("2013-06-30T12:34:56"), CommentText = "Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. " },
                new Comment { UserId = 1, ArticleId = 7, CommentDate = DateTime.Parse("2013-10-17T12:34:56"), CommentText = "Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc" },
                new Comment { UserId = 2, ArticleId = 8, CommentDate = DateTime.Parse("2013-09-04T12:34:56"), CommentText = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. " },
                new Comment { UserId = 5, ArticleId = 9, CommentDate = DateTime.Parse("2013-02-06T12:34:56"), CommentText = "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem." },
                new Comment { UserId = 3, ArticleId = 10, CommentDate = DateTime.Parse("2013-05-10T12:34:56"), CommentText = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?" },
                new Comment { UserId = 2, ArticleId = 11, CommentDate = DateTime.Parse("2013-11-25T12:34:56"), CommentText = "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga." },
                new Comment { UserId = 4, ArticleId = 12, CommentDate = DateTime.Parse("2013-08-23T12:34:56"), CommentText = "Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere " },
                new Comment { UserId = 4, ArticleId = 13, CommentDate = DateTime.Parse("2013-02-08T12:34:56"), CommentText = "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. " },
                new Comment { UserId = 1, ArticleId = 14, CommentDate = DateTime.Parse("2013-06-19T12:34:56"), CommentText = "Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores." },
                new Comment { UserId = 2, ArticleId = 15, CommentDate = DateTime.Parse("2013-03-22T12:34:56"), CommentText = "At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles. Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues." },
                new Comment { UserId = 5, ArticleId = 3, CommentDate = DateTime.Parse("2013-08-05T12:34:56"), CommentText = "It va esser tam simplic quam Occidental in fact, it va esser Occidental. " },
                new Comment { UserId = 2, ArticleId = 7, CommentDate = DateTime.Parse("2013-05-02T12:34:56"), CommentText = "A un Angleso it va semblar un simplificat Angles, quam un skeptic Cambridge amico dit me que Occidental es.Li Europan lingues es membres del sam familie." },
                new Comment { UserId = 3, ArticleId = 1, CommentDate = DateTime.Parse("2013-09-13T12:34:56"), CommentText = "Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. " },
                new Comment { UserId = 5, ArticleId = 3, CommentDate = DateTime.Parse("2013-10-29T12:34:56"), CommentText = "Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores." },
                new Comment { UserId = 4, ArticleId = 12, CommentDate = DateTime.Parse("2013-03-15T12:34:56"), CommentText = "At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles." },
            };

            comments.ForEach(s => context.Comments.AddOrUpdate(p => p.ArticleId, s));
            context.SaveChanges();
        }
    }
}
